### ISSUE TITLE
🚀 [feature] 디자이너 견적서 작성/수정/삭제 API 작성

### ISSUE THREAD

**Issue by sgn07124** [jjsOrganization/server#11]
# 🤖 기능 개요
디자이너 견적서 작성/수정/삭제 API 작성

## ✅ Todo
- [x] 디자이너의 견적서 작성 API 추가
- [x] 디자이너의 견적서 수정 API 추가
- [x] 디자이너의 견적서 삭제 API 추가

### 📚 Remarks
긴 글을 작성하는 타입 @Lob -> varchar(1000~2000) 으로 변경함
