### ISSUE TITLE
🚀 [feature] 리폼 형상관리 API 작성

### ISSUE THREAD

**Issue by sgn07124** [jjsOrganization/server#18]
# 🤖 기능 개요
디자이너는 구매자가 리폼 현황을 알 수 있도록 리폼 과정을 사진으로 보여준다.

## ✅ Todo
- [x] #22
- [x] 리폼 중인 사진 1 등록 API 추가(상태: 리폼 중)
- [x] 리폼 중인 사진 2 등록 API 추가
- [x] 리폼 완료된 사진 등록 API 추가(상태: 리폼 완료)

### 📚 Remarks
각 과정마다 리폼 상태가 변경되도록 해야 리폼 완료된 현상관리를 조회할 수 있음
