### ISSUE TITLE
🚀 [feature] 구매자가 리폼 수락 시 진행되는 주문 API

### ISSUE THREAD

**Issue by sgn07124** [jjsOrganization/server#30]
# 🤖 기능 개요
구매자가 리폼 견적서 수락 시 기존 상품에 리폼 비용을 추가한 총 비용이 나와야하며 개인정보(배송 정보, 개인 정보) 입력 후 리폼 수락이 완료된다.

과정 : 구매자 마이페이지(견적서 수락 버튼) -> 개인 정보 입력 창(다음으로 버튼) -> 총 비용이 표시되는 창(결제 및 수락 버튼) -> 수락 완료 후 다시 마이페이지로 이동

## ✅ Todo
- [x] 견적서 수락 버튼이 눌리면 해당 견적서에 대한 리폼 주문이 생성되는 API(리폼 주문 상태:`ORDERING`)
- [x] 견적서 거절 버튼이 눌리면 해당 견적서의 상태가 `REQUEST_REJECTED`로 변경되는 API
- [x] 입력받은 구매자 개인 정보를 ReformOrder 엔티티에 저장하는 API
- [x] 견적서 id로 총 가격 조회하는 API (총 비용, 리폼 비용, 상품 가격)
- [x] 견적서에 대한 리폼 및 상품을 결제 및 수락하는 API (견적서 상태:`REQUEST_ACCEPTED`, 리폼 주문 상태:`ORDER_COMPLETE`, 형상관리 상태:`REFORM_START`)

### 📚 Remarks
구매자의 견적서 상태 수정 API 삭제 후 총 비용이 표시되는 창에서 결제 및 수락 버튼을 누르면 결제가 완료되며 리폼 주문 상태가 변경되는 API에 해당 견적서 상태 수정 로직도 포함시켜야함.
