### ISSUE TITLE
🚀 [feature] 디자이너의 포트폴리오에 작업물 등록 API

### ISSUE THREAD

**Issue by sgn07124** [jjsOrganization/server#73]
# 🤖 기능 개요

디자이너는 리폼이 완료된 작업물을 자신의 포트폴리오에 등록할 수 있다. 리폼 완료 여부는 형상관리 마지막 사진이 등록되면 상태가 리폼 완료 상태가 되므로 형상관리id로 작업물이 생성된다.(작업물 생성 시 ProgressId가 필요하다.)

## ✅ Todo
- [x] 포트폴리오 작업물 등록 시, 고정 항목 조회 API → 작업물 등록 창에서 수정할 수 없는 항목들을 디자이너에게 보여주는 부분으로 디자이너명, 초기 사진, 구매자 요청 사진, 디자이너 견적 사진, 완성 사진, 리폼 기간, 리폼 가격, 리폼 부위를 조회한다. 
- [x] 포트폴리오 작업물 등록 API
- [x] 포트폴리오 작업물 수정 API
- [x] 포트폴리오 작업물 수정 시, 이전에 작성했던 내용(제목, 글) 조회 API
- [x] 포트폴리오 작업물들 조회 API
- [x] 포트폴리오 작업물 상세 조회 API

### 📚 Remarks

작업물의 작업 기간은 구매자가 작성한 요청서의 날짜와 디자이너가 형상관리의 마지막 사진을 등록한 시간(상태가 리폼 완료 상태로 변경)의 차이 +1로 계산된다.
