### ISSUE TITLE
🚀 [feature] 디자이너 포트폴리오, 작업물 API 수정

### ISSUE THREAD

**Issue by sgn07124** [jjsOrganization/server#87]
# 🤖 기능 개요

포트폴리오 등록,수정,조회에 가격표 이미지 추가. 작업물 고정항목 조회 시 요소 추가
## ✅ Todo
- [x] 포트폴리오 등록 API → 가격표 추가 등록 가능
- [x] 포트폴리오 수정 API → 가격표 수정 가능
- [x] 포트폴리오 조회(로그인) API → 가격표 이미지 url 추가
- [x] 포트폴리오 전체 조회 API → 가격표 이미지 url 추가
- [x] 작업물들을 리스트로 조회 API(/portfolio/reformOutput/list) → progressNumber(작업물id) 추가
- [x] 포트폴리오 작업물 등록 시, 고정 항목 조회 API(/portfolio/reformOutput/upload/{progressNumber}) → 상품명, 디자이너 프로필 사진(선택), 요청서의 리폼 요청사항, 견적서의 내용 추가
